---
permalink: sm-storage/create-synchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, synchronous, mirrored, volume 
summary: Une mise en miroir synchrone des volumes permet une réplication en temps réel des données entre les baies de stockage. Ainsi, vos informations sont protégées contre les défaillances système et site. Pour ce faire, sélectionnez le volume primaire et le volume secondaire que vous souhaitez utiliser dans la relation de mise en miroir synchrone entre une matrice de stockage locale et une matrice de stockage distante. 
---
= Création d'un volume mis en miroir synchrone
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une mise en miroir synchrone des volumes permet une réplication en temps réel des données entre les baies de stockage. Ainsi, vos informations sont protégées contre les défaillances système et site. Pour ce faire, sélectionnez le volume primaire et le volume secondaire que vous souhaitez utiliser dans la relation de mise en miroir synchrone entre une matrice de stockage locale et une matrice de stockage distante.

.Avant de commencer
* La fonctionnalité de mise en miroir synchrone requiert de gérer plusieurs baies de stockage. Par conséquent, SANtricity Unified Manager basé sur un navigateur est installé et vous avez découvert les deux baies de stockage entre elles que vous souhaitez mettre en miroir. Ensuite, dans Unified Manager, vous sélectionnez la baie de stockage du volume primaire, puis cliquez sur *Launch* pour ouvrir SANtricity System Manager basé sur navigateur.
* Vous devez disposer de deux baies de stockage.
* Chaque baie de stockage doit disposer de deux contrôleurs.
* Les baies de stockage des volumes primaires et secondaires peuvent exécuter différentes versions de systèmes d'exploitation. La version minimale prise en charge est 7.84.
* Vous devez connaître le mot de passe des matrices de stockage locales et distantes.
* Vos baies de stockage locales et distantes doivent être connectées via une structure Fibre Channel.
* Vous devez avoir créé à la fois les volumes primaires et secondaires que vous souhaitez utiliser dans la relation de miroir synchrone.


.Description de la tâche
Le processus de mise en miroir synchrone d'un volume est une procédure à plusieurs étapes :

* <<Étape 1 : sélectionnez le volume principal>>
* <<Étape 2 : sélectionnez le volume secondaire>>
* <<Étape 3 : sélectionnez les paramètres de synchronisation>>


Un volume ne peut participer qu'à une seule relation miroir.



== Étape 1 : sélectionnez le volume principal

[role="lead"]
Vous devez sélectionner le volume primaire que vous souhaitez utiliser dans la relation miroir synchrone. Ce volume contient le rôle principal dans la relation miroir.

.Avant de commencer
* Vous devez avoir créé le volume primaire que vous souhaitez utiliser dans la relation de miroir synchrone.
* Le volume primaire doit être un volume standard. Il ne peut s'agir d'un volume fin ou d'un volume de snapshot.


.Étapes
. Effectuez l'une des actions suivantes pour accéder à la séquence de mise en miroir synchrone :
+
** Sélectionner le menu :stockage[mise en miroir synchrone > Volume miroir].
** Sélectionner menu:Storage[volumes > Copy Services > Mirror a volume synchrone]. La boîte de dialogue *Créer une paire symétrique synchrone* apparaît.


. Sélectionnez un volume existant que vous souhaitez utiliser comme volume principal dans le miroir.
+
[NOTE]
====
Si un volume a été sélectionné dans la mosaïque volumes et qu'il peut être mis en miroir, il est sélectionné par défaut.

====
. Sélectionnez *Suivant* et allez à <<Étape 2 : sélectionnez le volume secondaire>>.




== Étape 2 : sélectionnez le volume secondaire

[role="lead"]
Vous devez sélectionner le volume secondaire que vous souhaitez utiliser dans la relation miroir. Ce volume maintient le rôle secondaire dans la relation miroir.

.Avant de commencer
* Vous devez avoir créé le volume secondaire que vous souhaitez utiliser dans la relation de miroir synchrone.
* Le volume secondaire doit être un volume standard. Il ne peut s'agir d'un volume fin ou d'un volume de snapshot.
* Le volume secondaire doit être au moins aussi grand que le volume primaire.


.Description de la tâche
Lorsque vous sélectionnez un volume secondaire sur la matrice de stockage distante, le système affiche la liste de tous les volumes éligibles pour cette paire en miroir. Les volumes qui ne peuvent pas être utilisés ne s'affichent pas dans cette liste.

Les volumes qui apparaissent dans cette boîte de dialogue sont triés par capacité, en commençant par le volume le plus proche de la capacité du volume primaire. Les volumes de capacité identique sont triés par ordre alphabétique.

.Étapes
. Sélectionnez la matrice de stockage distante sur laquelle vous souhaitez établir une relation de mise en miroir avec la matrice de stockage locale.
+
[NOTE]
====
Si votre matrice de stockage distante est protégée par un mot de passe, le système vous demande un mot de passe.

====
+
** Les baies de stockage sont répertoriées par le nom de leur baie de stockage. Si vous n'avez pas nommé de baie de stockage, elle est indiquée comme « sans nom ».
** Si la baie de stockage que vous souhaitez utiliser ne figure pas dans la liste, ajoutez-la à l'aide de la fenêtre de gestion d'entreprise (EMW) de SANtricity Storage Manager. Sélectionnez menu:Modifier[Ajouter une matrice de stockage].


. Sélectionnez un volume existant que vous souhaitez utiliser comme volume secondaire dans le miroir.
+
[NOTE]
====
Si un volume secondaire est choisi avec une capacité supérieure à celle du volume primaire, la capacité utilisable est limitée à la taille du volume primaire.

====
. Cliquez sur *Suivant* et allez à <<Étape 3 : sélectionnez les paramètres de synchronisation>>.




== Étape 3 : sélectionnez les paramètres de synchronisation

[role="lead"]
Vous devez définir la priorité à laquelle le propriétaire du contrôleur du volume principal resynchronise les données sur le volume secondaire après une interruption de communication. Vous devez également sélectionner la règle de resynchronisation manuelle ou automatique.

.Étapes
. Utilisez le curseur pour définir la priorité de synchronisation.
+
La priorité de synchronisation détermine la quantité de ressources système utilisées pour terminer la synchronisation initiale et l'opération de resynchronisation après une interruption de communication par rapport aux demandes d'E/S de service.

+
La priorité définie dans cette boîte de dialogue s'applique à la fois au volume primaire et au volume secondaire. Vous pouvez modifier ultérieurement le débit du volume principal en sélectionnant menu :stockage[mise en miroir synchrone > plus > Modifier les paramètres].

+
.En savoir plus sur les taux de synchronisation
[%collapsible]
====
Il existe cinq taux de priorité de synchronisation :

** La plus faible
** Faible
** Moyen
** Élevée
** Maximum si la priorité de synchronisation est définie sur le taux le plus bas, l'activité d'E/S est prioritaire et l'opération de resynchronisation prend plus de temps. Si la priorité de synchronisation est définie sur le taux le plus élevé, l'opération de resynchronisation est prioritaire, mais l'activité d'E/S de la matrice de stockage peut être affectée.


====
. Indiquez si vous souhaitez resynchroniser les paires mises en miroir sur la baie de stockage distante manuellement ou automatiquement.
+
** *Manuel* (option recommandée) -- sélectionnez cette option pour que la synchronisation puisse être reprise manuellement après la restauration de la communication sur une paire symétrique. Cette option offre la meilleure possibilité de récupérer des données.
** *Automatique* -- sélectionnez cette option pour démarrer la resynchronisation automatiquement après la restauration de la communication vers une paire symétrique. Pour reprendre la synchronisation manuellement, allez dans le menu :stockage[mise en miroir synchrone], mettez la paire symétrique en surbrillance dans le tableau et sélectionnez *reprendre* sous *plus*.


. Cliquez sur *Finish* pour terminer la séquence de mise en miroir synchrone.


.Résultats
System Manager effectue les actions suivantes :

* Active la fonction de mise en miroir synchrone.
* Commence la synchronisation initiale entre la matrice de stockage locale et la matrice de stockage distante.
* Définit la priorité de synchronisation et la règle de resynchronisation.


.Une fois que vous avez terminé
Sélectionner menu:Accueil[opérations de visualisation en cours] pour afficher la progression de l'opération de mise en miroir synchrone. Cette opération peut être longue et peut affecter les performances du système.
