---
permalink: sm-mirroring/considerations-for-setting-up-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: considerations, setting up, asynchronous, mirror 
summary: 'Pour garantir une configuration et une configuration performantes, gardez à l"esprit certains éléments clés de votre planification.' 
---
= Considérations relatives à la configuration de la mise en miroir asynchrone
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour garantir une configuration et une configuration performantes, gardez à l'esprit certains éléments clés de votre planification.



== Lancez SANtricity Unified Manager

* Chaque contrôleur de la baie primaire et de la baie secondaire doit disposer d'un port de gestion Ethernet configuré et être connecté à votre réseau.
* La mise en miroir asynchrone est configurée en ouvrant SANtricity Unified Manager. Toute relation de mise en miroir nécessite que les systèmes de stockage locaux et distants soient découverts et répertoriés dans SANtricity Unified Manager.
* Sur votre navigateur, vous devez installer SANtricity Unified Manager. Vous avez découvert les deux baies de stockage que vous souhaitez mettre en miroir des données entre elles. Ensuite, dans Unified Manager, vous sélectionnez la baie de stockage du volume primaire, puis cliquez sur lancer pour ouvrir SANtricity System Manager basé sur navigateur.




== Activation

Avant d'utiliser la mise en miroir asynchrone, vous devez l'activer sur chaque baie de stockage participant aux opérations de mise en miroir. L'activation peut s'effectuer via l'interface de ligne de commande, l'API REST ou l'interface utilisateur graphique de gestion.

* Pour les systèmes gérés par SANtricity System Manager (E2800, E5700, EF570), aucune étape d'activation distincte n'est nécessaire. L'activation s'effectue en arrière-plan pendant la configuration des groupes/paires de miroirs.
* Pour les systèmes gérés par SANtricity Storage Manager (E2700, E5600, EF560), la mise en miroir asynchrone est activée à l'aide de l'interface graphique du système existant non géré par SANtricity System Manager. Si vous utilisez iSCSI pour la mise en miroir asynchrone, l'étape d'activation n'est pas nécessaire.




== Certificats de services Web et navigateurs recommandés

* *Certificats de confiance*
+
Pour la mise en miroir impliquant des systèmes gérés par SANtricity System Manager, il est recommandé d'importer les certificats de confiance pour les services Web dans SANtricity Unified Manager qui permettent aux systèmes de stockage de s'authentifier auprès du serveur Web. Les étapes du programme SANtricity Unified Manager sont les suivantes :

+
.. Générez une demande de signature de certificat (CSR) pour l'ordinateur sur lequel SANtricity Unified Manager est installé.
.. Envoyez la RSC à une autorité de certification (CA).
.. Lorsque l'autorité de certification renvoie les certificats signés, importez-les dans Unified Manager.


* *Certificats auto-signés*
+
Les certificats auto-signés peuvent également être utilisés. Si l'administrateur tente de configurer la mise en miroir sans importer les certificats signés, SANtricity System Manager affiche une boîte de dialogue d'erreur qui permet à l'administrateur d'accepter le certificat auto-signé. Dans ce cas, il est recommandé d'utiliser la dernière version de Chrome ou de Firefox comme navigateur.

+
Vous pouvez accepter un certificat auto-signé ou installer votre propre certificat de sécurité à l'aide d'Unified Manager et accéder au menu :Certificate[Certificate Management].





== Connexions prises en charge

La mise en miroir asynchrone peut utiliser des connexions FC ou iSCSI, ou les deux, pour la communication entre les systèmes de stockage locaux et distants. Au moment de la création d'un groupe de cohérence en miroir (également appelé groupe de miroirs asynchrone), l'administrateur peut sélectionner FC ou iSCSI pour ce groupe si les deux sont connectés à la baie de stockage distante. Il n'y a pas de basculement d'un type de canal à l'autre.

La mise en miroir asynchrone utilise les ports d'E/S côté hôte de la baie de stockage pour transmettre les données en miroir du côté principal au côté secondaire.

* *Mise en miroir via une interface Fibre Channel (FC)*
+
Chaque contrôleur de la baie de stockage dédie son port hôte FC le plus numéroté aux opérations de mise en miroir.

+
Si le contrôleur possède à la fois des ports FC de base et des ports FC de carte d'interface hôte (HIC), le port le plus numéroté est situé sur une HIC. Tout hôte connecté au port dédié est déconnecté et aucune demande de connexion à l'hôte n'est acceptée. Les demandes d'E/S sur ce port sont acceptées uniquement à partir des contrôleurs qui participent aux opérations de mise en miroir.

+
Les ports dédiés à la mise en miroir doivent être connectés à un environnement FC Fabric qui prend en charge le service d'annuaire et les interfaces de service de noms. En particulier, les protocoles FC-AL et point à point ne sont pas pris en charge en tant qu'options de connectivité entre les contrôleurs participant aux relations en miroir.

* *Mise en miroir via une interface iSCSI*
+
Contrairement à FC, l'iSCSI ne nécessite pas de port dédié. Lorsqu'une mise en miroir asynchrone est utilisée dans les environnements iSCSI, il n'est pas nécessaire de dédier les ports iSCSI frontaux de la baie de stockage à une utilisation avec la mise en miroir asynchrone. Ces ports sont partagés à la fois pour le trafic en miroir asynchrone et les connexions d'E/S hôte à baie.

+
Le contrôleur maintient une liste de systèmes de stockage distants avec lesquels l'initiateur iSCSI tente d'établir une session. Le premier port qui établit avec succès une connexion iSCSI est utilisé pour toutes les communications ultérieures avec cette matrice de stockage distante. Si la communication échoue, une nouvelle session est tentée en utilisant tous les ports disponibles.

+
Les ports iSCSI sont configurés au niveau de la baie, port par port. La communication InterController pour la messagerie de configuration et le transfert de données utilise les paramètres globaux, notamment les paramètres suivants :

+
** VLAN : les systèmes locaux et distants doivent avoir le même paramètre VLAN pour communiquer
** Port d'écoute iSCSI
** Trames Jumbo
** Priorité Ethernet


+
[NOTE]
====
La communication iSCSI entre contrôleurs doit utiliser un port de connexion hôte et non le port Ethernet de gestion.

====


La mise en miroir asynchrone utilise les ports d'E/S côté hôte de la baie de stockage pour transmettre les données en miroir du côté principal au côté secondaire. Étant donné que la mise en miroir asynchrone est destinée aux réseaux à latence plus élevée et à moindre coût, les connexions iSCSI (par conséquent basées sur TCP/IP) sont particulièrement adaptées. Lorsqu'une mise en miroir asynchrone est utilisée dans les environnements iSCSI, il n'est pas nécessaire de dédier les ports iSCSI frontaux de la baie à utiliser avec la mise en miroir asynchrone. Ces ports sont partagés à la fois pour le trafic en miroir asynchrone et les connexions d'E/S hôte à baie
