---
permalink: sm-mirroring/create-asynchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, asynchronous, mirrored, volume 
summary: 'Il met en miroir un volume de façon asynchrone pour gérer les données au niveau de la baie de stockage distante afin qu"il s"agisse d"une copie cohérente et instantanée des données au niveau de la baie de stockage locale. Pour ce faire, créez un groupe de cohérence en miroir afin d"établir la relation entre les deux baies de stockage, puis sélectionnez le volume primaire et le volume secondaire que vous souhaitez utiliser dans le miroir.' 
---
= Création d'un volume mis en miroir asynchrone
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il met en miroir un volume de façon asynchrone pour gérer les données au niveau de la baie de stockage distante afin qu'il s'agisse d'une copie cohérente et instantanée des données au niveau de la baie de stockage locale. Pour ce faire, créez un groupe de cohérence en miroir afin d'établir la relation entre les deux baies de stockage, puis sélectionnez le volume primaire et le volume secondaire que vous souhaitez utiliser dans le miroir.

.Avant de commencer
* Les conditions suivantes doivent être définies :
+
** Le service Web Services Proxy est en cours d'exécution.
** SANtricity Unified Manager s'exécute sur votre hôte local via une connexion HTTPS.
** Chaque contrôleur de la baie primaire et de la baie secondaire doit disposer d'un port de gestion Ethernet configuré et être connecté à votre réseau.
** SANtricity Unified Manager affiche des certificats SSL valides pour la matrice de stockage. Vous pouvez accepter un certificat auto-signé ou installer votre propre certificat de sécurité à l'aide d'Unified Manager et accéder au menu :Certificate[Certificate Management].
** SANtricity System Manager est lancé à partir d'Unified Manager.
** Vous devez avoir découvert les deux baies de stockage entre elles que vous souhaitez mettre en miroir des données. Ensuite, dans Unified Manager, vous sélectionnez la baie de stockage du volume primaire, puis cliquez sur lancer pour ouvrir SANtricity System Manager basé sur navigateur.


* Vous devez connaître le mot de passe des matrices de stockage locales et distantes.
* Vos baies de stockage locales et distantes doivent être connectées via une structure Fibre Channel ou une interface iSCSI.


Le processus de mise en miroir asynchrone d'un volume est une procédure à plusieurs étapes :

*  1: Create a mirror consistency group or select an existing one
*  2: Select the primary volume
*  3: Select the secondary volume


Un volume ne peut participer qu'à une seule relation miroir.



== Étape 1 : créer un groupe de cohérence miroir ou sélectionner un groupe existant

[role="lead"]
Vous créez un groupe de cohérence miroir ou sélectionnez un groupe existant pour établir la relation de mise en miroir entre la matrice de stockage locale et la matrice de stockage distante.

Le nombre de relations de groupe de cohérence miroir et de relations de paire en miroir que vous pouvez créer dépend du matériel de votre matrice de stockage.

.Étapes
. Effectuez l'une des actions suivantes pour accéder à la séquence de mise en miroir asynchrone :
+
** Sélectionnez menu:Storage[Asynchronous Mirroring > Create miroite pair].
** Sélectionner le menu:Storage[volumes > Copy Services > Mirror a volume de manière asynchrone].


. Sélectionnez un groupe de cohérence miroir existant ou en créez un nouveau.
+
Pour créer un nouveau groupe de cohérence en miroir, procédez comme suit :

+
.. Entrez un nom unique qui décrit le mieux les données sur les volumes qui seront mis en miroir entre les deux baies de stockage (par exemple, données R&D).
.. Sélectionnez la matrice de stockage distante sur laquelle vous souhaitez établir une relation de mise en miroir avec la matrice de stockage locale.
+
[NOTE]
====
Si votre matrice de stockage distante est protégée par un mot de passe, le système vous demande un mot de passe.

====
.. Indiquez si vous souhaitez resynchroniser les paires mises en miroir sur la baie de stockage distante manuellement ou automatiquement.
+
*** *Manuel* -- vous devez mettre à jour explicitement l'image ponctuelle secondaire à l'aide de l'option de menu Réchronisation manuelle. Sélectionnez cette option pour démarrer manuellement la resynchronisation de toutes les paires asynchrones mises en miroir dans le groupe de miroirs asynchrones.
*** *Automatique* -- à l'aide de la liste déroulante, spécifiez l'heure entre le début de la mise à jour précédente et le début de la prochaine mise à jour. Pour modifier l'intervalle de synchronisation automatique par rapport à la valeur par défaut toutes les 10 minutes, modifiez la valeur de l'intervalle, qui est définie en minutes.


.. Cliquez sur Créer .
+
System Manager crée d'abord le groupe de cohérence miroir sur la baie de stockage locale, puis crée le groupe de cohérence miroir sur la baie de stockage distante.

+
[NOTE]
====
Si System Manager crée avec succès le groupe de cohérence miroir sur la baie de stockage locale, mais qu'il ne parvient pas à le créer sur la baie de stockage distante, il supprime automatiquement le groupe de cohérence miroir de la baie de stockage locale. En cas d'erreur lors de la suppression du groupe de cohérence miroir dans System Manager, vous devez le supprimer manuellement.

====


. Sélectionnez *Suivant* et allez à  2: Select the primary volume.




== Étape 2 : sélectionnez le volume principal

[role="lead"]
Vous devez sélectionner le volume primaire que vous souhaitez utiliser dans la relation de miroir et allouer sa capacité réservée. Tout volume ajouté au groupe de cohérence miroir sur la baie de stockage locale jouera le rôle principal dans la relation miroir.

.Étapes
. Sélectionnez un volume existant que vous souhaitez utiliser comme volume principal dans le miroir, puis cliquez sur *Suivant* pour allouer la capacité réservée.
. Attribuez la capacité réservée au volume principal sélectionné. Effectuez l'une des actions suivantes :
+
** *Acceptez les paramètres par défaut* -- utilisez cette option recommandée pour allouer la capacité réservée au volume principal avec les paramètres par défaut.
** *Allouez vos propres paramètres de capacité réservée pour répondre à vos besoins en stockage de données liés à la mise en miroir asynchrone* -- allouez la capacité réservée en suivant les directives suivantes.
+
*** Le paramètre par défaut pour la capacité réservée correspond à 20 % de la capacité du volume de base et cette capacité est généralement suffisante.
*** La capacité nécessaire varie, selon la fréquence et la taille des E/S écrites sur le volume primaire et le temps nécessaire pour conserver la capacité.
*** En général, choisissez une capacité supérieure pour la capacité réservée si l'une ou les deux conditions suivantes existent :
+
**** Vous avez l'intention de conserver la paire en miroir pendant une longue période.
**** Un pourcentage élevé de blocs de données change sur le volume primaire en raison d'une forte activité d'E/S. Utilisez des données de performances historiques ou d'autres utilitaires du système d'exploitation pour déterminer les activités d'E/S types sur le volume primaire.






. Sélectionnez *Suivant* et allez à  3: Select the secondary volume.




== Étape 3 : sélectionnez le volume secondaire

[role="lead"]
Vous devez sélectionner le volume secondaire à utiliser dans la relation de miroir et allouer sa capacité réservée. Tout volume ajouté au groupe de cohérence miroir sur la matrice de stockage distante contient le rôle secondaire dans la relation miroir.

Lorsque vous sélectionnez un volume secondaire sur la matrice de stockage distante, le système affiche la liste de tous les volumes éligibles pour cette paire en miroir. Les volumes qui ne peuvent pas être utilisés ne s'affichent pas dans cette liste.

.Étapes
. Sélectionnez un volume existant que vous souhaitez utiliser comme volume secondaire dans la paire en miroir, puis cliquez sur *Suivant* pour allouer la capacité réservée.
. Allouez la capacité réservée au volume secondaire sélectionné. Effectuez l'une des actions suivantes :
+
** *Acceptez les paramètres par défaut* -- utilisez cette option recommandée pour allouer la capacité réservée au volume secondaire avec les paramètres par défaut.
** *Allouez vos propres paramètres de capacité réservée pour répondre à vos besoins en stockage de données liés à la mise en miroir asynchrone* -- allouez la capacité réservée en suivant les directives suivantes.
+
*** Le paramètre par défaut pour la capacité réservée correspond à 20 % de la capacité du volume de base et cette capacité est généralement suffisante.
*** La capacité nécessaire varie, selon la fréquence et la taille des E/S écrites sur le volume primaire et le temps nécessaire pour conserver la capacité.
*** En général, choisissez une capacité supérieure pour la capacité réservée si l'une ou les deux conditions suivantes existent :
+
**** Vous avez l'intention de conserver la paire en miroir pendant une longue période.
**** Un pourcentage élevé de blocs de données change sur le volume primaire en raison d'une forte activité d'E/S. Utilisez des données de performances historiques ou d'autres utilitaires du système d'exploitation pour déterminer les activités d'E/S types sur le volume primaire.






. Sélectionnez *Finish* pour terminer la séquence de mise en miroir asynchrone.


System Manager effectue les actions suivantes :

* Commence la synchronisation initiale entre la matrice de stockage locale et la matrice de stockage distante.
* Si le volume mis en miroir est un volume fin, seuls les blocs provisionnés (capacité allouée plutôt que capacités signalées) sont transférés vers le volume secondaire au cours de la synchronisation initiale. Cela réduit la quantité de données à transférer pour terminer la synchronisation initiale.
* Crée la capacité réservée pour la paire en miroir sur la matrice de stockage locale et sur la matrice de stockage distante.

