---
permalink: sm-mirroring/requirements-for-using-synchronous-mirroring.html 
sidebar: sidebar 
keywords: requirements, synchronous, mirroring 
summary: 'Si vous utilisez la fonction de mise en miroir synchrone, gardez les exigences suivantes à l"esprit.' 
---
= Requise pour l'utilisation de la mise en miroir synchrone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez la fonction de mise en miroir synchrone, gardez les exigences suivantes à l'esprit.



== SANtricity Unified Manager

La fonctionnalité de mise en miroir synchrone requiert de gérer plusieurs baies de stockage. Par conséquent, SANtricity Unified Manager basé sur un navigateur est installé et vous avez découvert les deux baies de stockage entre elles que vous souhaitez mettre en miroir. Ensuite, dans Unified Manager, vous sélectionnez la baie de stockage du volume primaire, puis cliquez sur lancer pour ouvrir SANtricity System Manager basé sur navigateur.



== Les baies de stockage

* Vous devez disposer de deux baies de stockage.
* Chaque baie de stockage doit disposer de deux contrôleurs.
* Les baies de stockage des volumes primaires et secondaires peuvent exécuter différentes versions de systèmes d'exploitation. La version minimale prise en charge est 7.84.
* Vous devez connaître le mot de passe des matrices de stockage locales et distantes.
* Vous devez disposer d'une capacité disponible suffisante sur la matrice de stockage distante pour créer un volume secondaire égal ou supérieur au volume principal que vous souhaitez mettre en miroir.
* Vos baies de stockage locales et distantes doivent être connectées via une structure Fibre Channel.




== Configuration matérielle et connexions prises en charge

* La mise en miroir synchrone est prise en charge uniquement dans les configurations matérielles à double contrôleur.
* Les communications destinées à la mise en miroir synchrone sont uniquement prises en charge sur les contrôleurs avec des ports hôte Fibre Channel (FC).
* La mise en miroir synchrone utilise le port hôte numéro le plus élevé sur chaque contrôleur à la fois sur la matrice de stockage locale et sur la baie de stockage distante. Le port hôte 4 de l'adaptateur de bus hôte (HBA) du contrôleur est généralement réservé à la transmission de données en miroir.




== Candidats aux volumes en miroir

* Le niveau RAID, les paramètres de mise en cache et la taille des segments peuvent être différents sur les volumes primaire et secondaire d'une paire synchrone en miroir.
* Les volumes primaires et secondaires d'une paire mise en miroir synchrone doivent être des volumes standard. Elles ne peuvent pas être de volumes fins ou de snapshot.
* Le volume secondaire doit être au moins aussi grand que le volume primaire.
* Seul le volume primaire peut avoir des snapshots associés et/ou être le volume source ou cible dans une opération de copie de volume.
* Un volume ne peut participer qu'à une seule relation miroir.




== Capacité réservée

* Une capacité réservée est requise pour un volume primaire et un volume secondaire pour les informations de journalisation en écriture afin de restaurer les données à partir de la réinitialisation du contrôleur et d'autres interruptions temporaires.
* Les volumes de capacité réservée sont créés automatiquement lorsque la mise en miroir synchrone est activée. Comme le volume primaire et le volume secondaire d'une paire en miroir nécessitent une capacité réservée, vous devez disposer d'une capacité disponible suffisante sur les deux baies de stockage participant à la relation de miroir synchrone.




== Fonction de sécurité du lecteur

* Si vous utilisez des lecteurs sécurisés, le volume principal et le volume secondaire doivent disposer de paramètres de sécurité compatibles. Cette restriction n'est pas appliquée ; vous devez donc la vérifier vous-même.
* Si vous utilisez des lecteurs sécurisés, le volume principal et le volume secondaire doivent utiliser le même type de lecteur. Cette restriction n'est pas appliquée ; vous devez donc la vérifier vous-même.
+
** Si le volume primaire utilise des disques FDE (Full Disk Encryption), le volume secondaire doit utiliser des disques FDE.
** Si le volume primaire utilise des disques validés conformes à la norme FIPS 140-2 (Federal information Processing Standards), le volume secondaire doit utiliser des disques validés conformes à la norme FIPS 140-2.


* Si vous utilisez Data assurance (DA), le volume primaire et le volume secondaire doivent avoir les mêmes paramètres DA.

