---
permalink: sm-mirroring/synchronous-mirroring-what-do-i-need-to-know-before-creating-a-mirrored-pair.html 
sidebar: sidebar 
keywords: synchronous, mirroring, create, mirrored path 
summary: Avant de créer une paire en miroir, assurez-vous que votre environnement respecte les consignes suivantes. 
---
= Mise en miroir synchrone : que faut-il savoir avant de créer une paire en miroir ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de créer une paire en miroir, assurez-vous que votre environnement respecte les consignes suivantes.

* Vous devez disposer d'une capacité disponible suffisante sur la matrice de stockage distante pour créer un volume secondaire égal ou supérieur au volume principal que vous souhaitez mettre en miroir.
* Vous devez disposer de deux baies de stockage.
* Chaque baie de stockage doit disposer de deux contrôleurs.
* Vous devez connaître le mot de passe des matrices de stockage locales et distantes.
* Vos baies de stockage locales et distantes doivent être connectées via une structure Fibre Channel.
* Vous devez avoir découvert les deux baies de stockage entre elles que vous souhaitez mettre en miroir des données. Ensuite, dans Unified Manager, vous sélectionnez la baie de stockage du volume primaire, puis cliquez sur lancer pour ouvrir SANtricity System Manager basé sur navigateur.

