---
permalink: sm-settings/configure-nvme-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, infiniband, ports 
summary: 'Si votre contrôleur inclut une connexion NVMe over InfiniBand, vous pouvez configurer les paramètres du port NVMe à partir de la page Hardware (matériel) ou System (système).' 
---
= Configurer les ports NVMe over InfiniBand
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si votre contrôleur inclut une connexion NVMe over InfiniBand, vous pouvez configurer les paramètres du port NVMe à partir de la page Hardware (matériel) ou System (système).

.Avant de commencer
* Votre contrôleur doit inclure un port hôte NVMe over InfiniBand. Sinon, les paramètres NVMe over InfiniBand ne sont pas disponibles dans System Manager.
* Vous devez connaître l'adresse IP de la connexion hôte.


Vous pouvez accéder à la configuration NVMe over InfiniBand à partir de la page *Hardware* ou du menu:Settings[System]. Cette tâche décrit comment configurer les ports à partir de la page *Hardware*.

[NOTE]
====
Les paramètres et les fonctions de NVMe over InfiniBand n'apparaissent que si le contrôleur de votre baie de stockage est équipé d'un port NVMe over InfiniBand.

====
.Étapes
. Sélectionnez *matériel*.
. Si le graphique montre les lecteurs, cliquez sur *Afficher le verso du tiroir*.
+
Le graphique change pour afficher les contrôleurs au lieu des disques.

. Cliquez sur le contrôleur associé au port NVMe over InfiniBand que vous souhaitez configurer.
+
Le menu contextuel du contrôleur s'affiche.

. Sélectionnez *configurer NVMe sur les ports InfiniBand*.
+
La boîte de dialogue *Configure NVMe over InfiniBand ports* s'ouvre.

. Dans la liste déroulante, sélectionnez le port HIC que vous souhaitez configurer, puis entrez l'adresse IP de l'hôte.
. Cliquez sur *configurer*.
. Terminez la configuration, puis réinitialisez le port NVMe over InfiniBand en cliquant sur *Yes*.

