---
permalink: sm-settings/obtain-a-feature-key-file.html 
sidebar: sidebar 
keywords: obtain, feature, key, file 
summary: 'Pour activer une fonction premium ou un pack de fonctionnalités sur votre matrice de stockage, vous devez d"abord obtenir un fichier de clé de fonction. Une clé n"est associée qu"à une seule baie de stockage.' 
---
= Obtenir un fichier de clé de fonction
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour activer une fonction premium ou un pack de fonctionnalités sur votre matrice de stockage, vous devez d'abord obtenir un fichier de clé de fonction. Une clé n'est associée qu'à une seule baie de stockage.

Dans cette tâche, vous apprendrez à rassembler les informations requises pour la fonction, puis à envoyer une demande pour un fichier de clé de fonction. Informations requises :

* Numéro de série du châssis
* Identifiant d'activation de fonctionnalité
* Code d'activation de la fonction


.Étapes
. Dans System Manager, recherchez et enregistrez le numéro de série du châssis. Vous pouvez afficher ce numéro de série en plaçant votre souris sur la mosaïque du Centre de support.
. Dans System Manager, localisez l'identifiant d'activation de la fonction. Accédez au menu:Paramètres[système], puis faites défiler jusqu'à *Compléments*. Recherchez l'identifiant *Feature Enable identifier*. Notez le numéro de l'identifiant d'activation de la fonction.
. Localisez et enregistrez le code d'activation de la fonction. Pour les packs de fonctionnalités, ce code d'activation est fourni dans les instructions appropriées pour effectuer la conversion.
+
Des instructions NetApp sont disponibles à partir de http://mysupport.netapp.com/info/web/ECMP1658252.html["Centre de documentation des systèmes NetApp E-Series"^].

+
Pour les fonctionnalités Premium, vous pouvez accéder au code d'activation à partir du site de support, comme suit :

+
.. Connectez-vous à http://mysupport.netapp.com["Support NetApp"^].
.. Accédez au menu:produits [gérer les produits > licences logicielles].
.. Entrez le numéro de série du châssis de la matrice de stockage, puis cliquez sur *Go*.
.. Recherchez les codes d'activation de la fonction dans la colonne *clé de licence*.
.. Enregistrez le code d'activation de la fonction souhaitée.


. Demandez un fichier de clé de fonction en envoyant un e-mail ou un document texte à votre fournisseur de stockage contenant les informations suivantes : numéro de série du châssis, code d'activation de la fonction et identifiant d'activation de la fonction.
+
Vous pouvez également accéder à http://partnerspfk.netapp.com["Activation de licence NetApp : activation de la fonctionnalité Storage Array Premium"^] saisissez les informations requises pour obtenir le pack de fonctions ou de fonctionnalités. (Les instructions de ce site concernent les fonctionnalités premium et non les packs de fonctionnalités.)



Lorsque vous disposez d'un fichier de clé de fonction, vous pouvez activer la fonction premium ou le pack de fonctions.
