---
permalink: sm-support/view-nvme-over-fabrics-statistics-support.html 
sidebar: sidebar 
keywords: view, nvme, fabrics, statistics 
summary: Vous pouvez afficher les données relatives aux connexions NVMe over Fabrics avec votre baie de stockage. 
---
= Affichez les statistiques NVMe over Fabrics
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les données relatives aux connexions NVMe over Fabrics avec votre baie de stockage.

.Description de la tâche
System Manager affiche ces types de statistiques NVMe over Fabrics. Toutes les statistiques sont en lecture seule et ne peuvent pas être définies.

* *Statistiques de sous-système NVMe* -- fournit des statistiques pour le contrôleur NVMe, y compris les délais et les échecs de connexion.
* *Statistiques de l'interface RDMA* -- fournit des statistiques pour l'interface RDMA, y compris les informations de paquets reçus et transmis.


Vous pouvez afficher chacune de ces statistiques sous forme de statistiques brutes ou en tant que statistiques de base. Les statistiques brutes sont toutes les statistiques collectées depuis le démarrage des contrôleurs. Les statistiques de référence sont des statistiques ponctuelles qui ont été recueillies depuis que vous avez défini l'heure de référence.

Vous pouvez accéder aux statistiques NVMe over Fabrics à partir de la page System (menu:Settings[System]) ou à partir de la page support. Ces instructions expliquent comment accéder aux statistiques à partir de la page support.

.Étapes
. Sélectionnez l'onglet support[Centre de support > Diagnostics].
. Sélectionnez *Afficher les statistiques NVMe over Fabrics*.
. Pour définir la ligne de base, cliquez sur *définir la nouvelle ligne de base*.
+
La définition de la ligne de base définit un nouveau point de départ pour la collecte des statistiques. La même base est utilisée pour toutes les statistiques NVMe.


