---
permalink: sm-support/view-nvme-over-infiniband-statistics-support.html 
sidebar: sidebar 
keywords: view, nvme, infiniband, statistics, packages 
summary: Vous pouvez afficher les données des connexions NVMe over InfiniBand avec votre baie de stockage. 
---
= Afficher les packages de statistiques NVMe over InfiniBand
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les données des connexions NVMe over InfiniBand avec votre baie de stockage.

System Manager affiche ces types de statistiques NVMe over InfiniBand. Toutes les statistiques sont en lecture seule et ne peuvent pas être définies.

* *Statistiques du contrôleur NVMe* -- fournit des statistiques sur le contrôleur NVMe, y compris les délais et les échecs de connexion.
* *Statistiques de file d'attente NVMe* -- fournit des statistiques pour la file d'attente NVMe, y compris les demandes de connexion et l'état des commandes.


Vous pouvez afficher chacune de ces statistiques sous forme de statistiques brutes ou en tant que statistiques de base. Les statistiques brutes sont toutes les statistiques collectées depuis le démarrage des contrôleurs. Les statistiques de référence sont des statistiques ponctuelles qui ont été recueillies depuis que vous avez défini l'heure de référence.

Vous pouvez accéder aux statistiques NVMe over InfiniBand à partir de la page système (menu:Settings[System]) ou à partir de la page support. Ces instructions expliquent comment accéder aux statistiques à partir de la page support.

.Étapes
. Sélectionnez l'onglet support[Centre de support > Diagnostics].
. Sélectionnez *Afficher les packages de statistiques NVMe sur InfiniBand*.
. Pour définir la ligne de base, cliquez sur *définir la nouvelle ligne de base*.
+
La définition de la ligne de base définit un nouveau point de départ pour la collecte des statistiques. La même base est utilisée pour toutes les statistiques NVMe.


